---
version: '3.8'
services:
#
# >>> mongodb
#
  db:
    image: mongo:4.4.2
    ports:
      - 27017:27017
    volumes:
      - "./docker/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
      - db
# <<< mongodb